"""Failure status constants shared across the engine, mirroring Arm B v2-P6."""

SUBMITTED = "submitted"
FAIL_TIMEOUT = "FAIL_TIMEOUT"
FAIL_NO_SUBMIT = "FAIL_NO_SUBMIT"
FAIL_NO_HYPOTHESIS = "FAIL_NO_HYPOTHESIS"
FAIL_EXCEPTION = "FAIL_EXCEPTION"

ALL_FAIL = {FAIL_TIMEOUT, FAIL_NO_SUBMIT, FAIL_NO_HYPOTHESIS, FAIL_EXCEPTION}
